# Generated by Django 2.2.28 on 2023-03-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20230306_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='USD', max_length=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsored_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsored_event_dedication',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
