from django.urls import path, re_path, include
from multimedia import views

urlpatterns = [
    re_path(r"^media-redirect/(?P<recording_id>\d+)/$", views.media_redirect,
        name="media_redirect"),
    re_path(r"^update_media_viewcount/$", views.update_media_viewcount,
        name="update_media_viewcount"),
    re_path(r"^most-popular-videos/$", views.most_popular_videos,
        name="most_popular_videos"),
    re_path(r"^most-popular-weekly-videos/$", views.most_popular_weekly_videos,
        name="most_popular_weekly_videos"),
    re_path(r"^most-recent-videos/$", views.most_recent_videos,
        name="most_recent_videos"),
    re_path(r"^most-popular-audio/$", views.most_popular_audio,
        name="most_popular_audio"),
    re_path(r"^most-popular-weekly-audio/$", views.most_popular_weekly_audio,
        name="most_popular_weekly_audio"),
    re_path(r"^most-recent-audio/$", views.most_recent_audio,
        name="most_recent_audio"),
    re_path(r"^upload_track/$", views.upload_track,
        name="upload_track", kwargs={'category': 'track'}),
    re_path(r"^upload_track_preview/$", views.upload_track,
        name="upload_track_preview", kwargs={'category': 'preview'}),
    re_path(r'^upload_image_preview/$', views.upload_image_preview,
        name="upload_image_preview"),
    re_path(r"^my-downloads/$", views.new_downloads, name="my-downloads"),
    re_path(r"^new-downloads/$", views.new_downloads, name="new-downloads"),
    re_path(r'^library/(?P<pk>\d+)$', views.album_view, name='album_view'),
    re_path(r'^downloads/(?P<pk>\d+)$', views.download_view, name='download_view'),
    re_path(r'^library/add-tracks$', views.add_tracks, name='add_tracks'),
]
