# Generated by Django 2.2.28 on 2023-03-23 18:47

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0025_auto_20230306_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '580x580', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text='Enable cropping', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='artistearnings',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='artistearnings',
            name='payout_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_earnings', to='artists.PastPayoutPeriod'),
        ),
        migrations.AlterField(
            model_name='pastpayoutperiod',
            name='admin_payout_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts/'),
        ),
        migrations.AlterField(
            model_name='pastpayoutperiod',
            name='donations_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts/'),
        ),
        migrations.AlterField(
            model_name='pastpayoutperiod',
            name='musicians_payout_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts/'),
        ),
        migrations.AlterField(
            model_name='payoutperiodgeneration',
            name='admin_payout_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts_generation/'),
        ),
        migrations.AlterField(
            model_name='payoutperiodgeneration',
            name='donations_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts_generation/'),
        ),
        migrations.AlterField(
            model_name='payoutperiodgeneration',
            name='musicians_payout_spreadsheet',
            field=models.FileField(blank=True, storage=storages.backends.s3boto.S3BotoStorage(), upload_to='payouts_generation/'),
        ),
        migrations.AlterField(
            model_name='payoutperiodgeneration',
            name='status',
            field=models.CharField(blank=True, choices=[('initial', 'initial'), ('processing', 'processing'), ('success', 'success'), ('error', 'error')], max_length=255),
        ),
    ]
