# Generated by Django 3.2 on 2024-08-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230323_1447'),
        ('customer', '0005_auto_20181115_1953'),
    ]

    operations = [
    ]
