# Generated by Django 3.2 on 2024-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20240822_1112'),
        ('customer', '0006_merge_0002_auto_20230323_1447_0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunicationEventType',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='productalert',
            options={'ordering': ['-date_created'], 'verbose_name': 'Product alert', 'verbose_name_plural': 'Product alerts'},
        ),
        migrations.AlterField(
            model_name='productalert',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='productalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
