# Generated by Django 2.2 on 2023-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20230323_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_link',
            field=models.CharField(blank=True, default=False, help_text='External Link of this product', max_length=500, null=True),
        ),
    ]
