# Generated by Django 2.2 on 2023-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_product_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_link',
            field=models.CharField(blank=True, help_text='External Link of this product', max_length=500, null=True),
        ),
    ]
