# Generated by Django 2.2 on 2023-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20231030_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_link',
            field=models.CharField(blank=True, default='', help_text='External Link of this product', max_length=500, null=True),
        ),
    ]
