# Generated by Django 3.2 on 2026-02-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
        ('catalogue', '0033_auto_20231030_0724'),
    ]

    operations = [
    ]
