# Generated by Django 2.2.28 on 2023-03-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_smallsuser_archive_access_until'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smallsuser',
            managers=[
                ('objects', users.models.SmallsUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='legalagreementacceptance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_agreement_acceptance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('48-hour pass', '48-hour pass'), ('Half Year Membership', 'Half Year Membership'), ('Monthly Pass', 'Monthly Pass'), ('Three Month Membership', 'Three Month Membership'), ('admin', 'admin'), ('basic membership', 'basic membership'), ('benefactor_1', 'benefactor_1'), ('benefactor_2', 'benefactor_2'), ('benefactor_3', 'benefactor_3'), ('member', 'member'), ('musician', 'musician'), ('smallslive membership', 'smallslive membership'), ('supporter', 'supporter'), ('trialMember', 'trialMember')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='institutional_subscriptions.Institution'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a VIP and has access to audio and video without paying for a subscription'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='payout_method',
            field=models.CharField(choices=[('Check', 'Check'), ('PayPal', 'PayPal')], default='Check', max_length=10),
        ),
        migrations.AlterField(
            model_name='smallsuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photos'),
        ),
    ]
