# Generated by Django 2.2 on 2023-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230323_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallsuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('48-hour pass', '48-hour pass'), ('Half Year Membership', 'Half Year Membership'), ('Monthly Pass', 'Monthly Pass'), ('Three Month Membership', 'Three Month Membership'), ('admin', 'admin'), ('basic membership', 'basic membership'), ('benefactor_1', 'benefactor_1'), ('benefactor_2', 'benefactor_2'), ('benefactor_3', 'benefactor_3'), ('member', 'member'), ('musician', 'musician'), ('smallslive membership', 'smallslive membership'), ('supporter', 'supporter'), ('trialMember', 'trialMember')], default='member', max_length=30),
        ),
    ]
