# Generated by Django 3.2 on 2026-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20230323_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_excl_tax',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='price_retail',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
