# Generated by Django 2.2 on 2026-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20230323_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='event_set_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
