# Generated by Django 3.2 on 2024-08-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20230323_1447'),
        ('order', '0008_auto_20190301_1035'),
    ]

    operations = [
    ]
