# Generated by Django 2.2.28 on 2023-04-30 17:11

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_auto_20170808_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=djstripe.fields.StripeTextField(blank=True, help_text='A description of this object.', null=True),
        ),
        # migrations.AlterField(
        #     model_name='charge',
        #     name='disputed',
        #     field=djstripe.fields.StripeBooleanField(default=False, help_text='Whether or not this charge is disputed.'),
        # ),
        # migrations.AlterField(
        #     model_name='charge',
        #     name='stripe_timestamp',
        #     field=djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True),
        # ),
    ]
