# Generated by Django 2.2.28 on 2023-05-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_auto_20230430_1311'),
        ('djstripe', '0029_auto_20180604_0751'),
    ]

    operations = [
    ]
