# Generated by Django 2.2.28 on 2023-03-23 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_eventset_walk_in_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.EventSet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('IR', 'In Review')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=events.models.CustomImageField(blank=True, max_length=150, storage=events.models.get_event_media_storage, upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='set',
            field=models.CharField(blank=True, choices=[('22:00-23:00', '10-11pm'), ('23:00-0:00', '11-12pm'), ('0:00-1:00', '12-1am')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
        migrations.AlterField(
            model_name='eventset',
            name='audio_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_is_audio', to='events.Recording'),
        ),
        migrations.AlterField(
            model_name='eventset',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventset',
            name='video_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_is_video', to='events.Recording'),
        ),
        migrations.AlterField(
            model_name='gigplayed',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_played', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='gigplayed',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_gig_info', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='gigplayed',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Instrument'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='media_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='multimedia.MediaFile'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Published', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='showdefaulttime',
            name='title',
            field=models.CharField(default='Set duration', max_length=100),
        ),
        migrations.AlterField(
            model_name='showdefaulttime',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_times', to='events.Venue'),
        ),
        migrations.AlterField(
            model_name='staffpick',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_picked', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='audio_bucket_name',
            field=models.CharField(default='smallslivemp3', max_length=4096),
        ),
        migrations.AlterField(
            model_name='venue',
            name='video_bucket_name',
            field=models.CharField(default='smallslivevid', max_length=4096),
        ),
    ]
