# Generated by Django 2.2 on 2026-02-24 08:07

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20230323_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='JazzCulturalPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', events.models.CustomImageField(max_length=150, storage=events.models.get_event_media_storage, upload_to='event_images')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'JazzCulturalPhotos',
                'verbose_name_plural': 'JazzCulturalPhotos',
                'db_table': 'jazzcultural_photos',
            },
        ),
    ]
