# Generated by Django 2.2 on 2026-03-05 10:22

from django.db import migrations, models
import django.db.models.deletion
import multimedia.s3_storages
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_jazzculturalphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clonned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='jazzculturalphotos',
            name='photo',
            field=models.ImageField(max_length=150, storage=multimedia.s3_storages.ImageS3Storage(access_key=settings.AWS_ACCESS_KEY_ID_JAZZCULTURAL, bucket='jazzculturalstatic', secret_key=settings.AWS_SECRET_ACCESS_KEY_JAZZCULTURAL), upload_to='jazzcultural_photos'),
        ),
    ]
