# Generated by Django 2.2 on 2026-09-25 10:56

from django.db import migrations, models
import multimedia.s3_storages


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20260305_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventset',
            name='external_ticket_label',
            field=models.CharField(blank=True, max_length=40, verbose_name='Third-party button text'),
        ),
        migrations.AddField(
            model_name='eventset',
            name='external_ticket_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Third-party ticket URL'),
        ),
        migrations.AlterField(
            model_name='jazzculturalphotos',
            name='photo',
            field=models.ImageField(max_length=150, storage=multimedia.s3_storages.JazzCulturalPhotosS3Storage(), upload_to='jazzcultural_photos'),
        ),
    ]
