# Generated by Django 2.2.28 on 2023-03-23 18:47

from django.db import migrations, models
import django.db.models.deletion
import multimedia.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_imagemediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemediafile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photos'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.MediaType'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='category',
            field=models.CharField(blank=True, choices=[('set', 'set'), ('track', 'track'), ('preview', 'preview')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='format',
            field=models.CharField(choices=[('mp3', 'mp3'), ('flac', 'flac'), ('wav', 'wav'), ('ogg', 'ogg'), ('mp4', 'mp4'), ('mpg', 'mpg'), ('avi', 'avi'), ('mkv', 'mkv'), ('mov', 'mov'), ('mpeg', 'mpeg'), ('flv', 'flv'), ('m4v', 'm4v')], editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='sd_video_file',
            field=multimedia.fields.DynamicBucketFileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
